Use `figure`/`figcaption` instead of `div` for illos
DistributedProofreaders/guiguts pull request #1052
Opened 2022-11-07 10:34 UTC by windymilla

Now GG is producing HTML5, take advantage of the new `figure` and `figcaption` elements. One advantage should be that the caption should not get separated from the illo by a page break in epub format.

Fixes #1045

2022-11-07 15:21 UTC, rtonsing commented
For `<figcaption>`, I think we can leave out the `class=\"caption\"`, since we can just override the tag in CSS. Not a deal breaker, though.

2022-11-07 15:25 UTC, rtonsing requested changes
For `<figcaption>`, I think we can leave out the `class=\"caption\"`, since we can just override the tag in CSS. Not a deal breaker, though.

2022-11-07 15:31 UTC, windymilla commented
> For `<figcaption>`, I think we can leave out the `class=\"caption\"`, since we can just override the tag in CSS. Not a deal breaker, though.

I wondered about that. I thought it was perhaps more friendly to the PPer to have a class for them to modify, especially if there are different caption styles within a book and they might then have two different classes, e.g. caption1 (italic, right justified) and caption2 (bold, centered). I don't mind removing it if people feel that's best though.

2022-11-07 20:34 UTC, rtonsing approved these changes

2022-11-08 01:12 UTC, cpeel approved these changes

2022-11-10 21:12 UTC, windymilla commented
Sorry, @srjfoo, I didn't leave any testing notes - there's no rush for testing it, but for when you get onto it...

If you have the text `[Illustration: Some caption]` in a file, then use HTML->HTML Generator, then Auto Illus Search, it will find the next [Illustration] and pop a dialog for you to choose a jpeg. It will pre-fill the caption field if you have a caption in the markup already, or you can type into it. When you click OK it inserts HTML markup - with this PR it should use figure and figcaption instead of divs. You can also "Insert & Load Next", which means to add the markup for this illo and jump to the next illo in the file. It automatically chooses the next jpeg file alphabetically, which you can adjust with the Prev file/Next file buttons.

An alternative if you don't have [Illustration] is to use HTML->HTML Markup, then choose Image from the Links section. The same dialog as above pops up and you can just insert the markup at the current location.

2022-11-14 19:37 UTC, srjfoo approved these changes

2022-11-15 09:07 UTC, merged